name: Bug report
description: Report a bug or issue
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for contributing!

        Please ensure the issue is not a duplicate.

        For security-related bugs, please don't file an issue, instead, see the "Report a Vulnerability" section in the contributing.md file.
  - type: textarea
    attributes:
      label: Bug description
      placeholder: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: Describe how to reproduce the bug.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: Describe the expected behavior.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual behavior
      placeholder: Describe the actual behavior.
    validations:
      required: false
  - type: textarea
    attributes:
      label: System information
      description: On Unix-like systems, please paste the output of `uname -a` here.
      placeholder: |
        Provide details about your environment, such as:

        - OS: Linux 6.12, Windows-10, macOS-14
        - Project version: 1.2.3
        - Tools: CMake 3.28, GCC 12.2.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Media
      placeholder: Provide videos, images and logs.
    validations:
      required: false
