name: Feature request
description: Propose a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for contributing!

        Please check if the feature request already exists before submitting.
  - type: textarea
    attributes:
      label: Feature description
      placeholder: Provide a clear description of the proposed feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reason
      placeholder: Explain why this feature would be useful.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Implementation idea
      placeholder: Share any ideas on how this feature could be implemented.
    validations:
      required: false

