name: Question
description: Ask a question
labels: ["question"]
body:
- type: markdown
  attributes:
    value: >
      Please ensure the feature request is not a duplicate.
- type: textarea
  attributes:
    label: Question
  validations:
    required: true
